icon: 'https://benji.pw/assets/icons/t.png'
version: 'Public Beta 1.1.0'
v: 'v=b1.1.0' # V is for "versioning" assets with query strings

# Root must be followed by a slash `/`
root: 'https://benji.pw/tchat'
accent: '#448aff'
